### ISSUE TITLE
Ejercicio 2 -c) Cómo implementaría el circuito de acondicionamiento de un fotodiodo...(Completo abriendo la issue)

### ISSUE THREAD

**Issue by GiseRomero** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-3er-semana-grupo-4#11]
Ejercicio 2 -c) Cómo implementaría el circuito de acondicionamiento de un fotodiodo utilizado para detectar contraste en un auto robot seguidor de línea.

**Comment by FedeBirge** [comment]
Hecho
