### ISSUE TITLE
Ejercicio 2 -Implemente un control de velocidad, posición y sentido de giro utilizando un motor con encoder incremental

### ISSUE THREAD

**Issue by GiseRomero** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-3er-semana-grupo-4#9]
Ejercicio 2 -Implemente un control de velocidad, posición y sentido de giro utilizando un motor con encoder incremental, el control del motor se debe realizar con pwm.

**Comment by estebancarrizo** [comment]
Se agrego trabajo 2a
